### ISSUE TITLE
tokenizer 在哪里下载

### ISSUE THREAD

**Issue by ljiuyuan1987** [MegEngine/InferLLM#19]
你好，请问去哪里下载 tokenizer 的文件到本地

**Comment by chenqy4933** [comment]
tokenizer 的 vocabulary 已经和模型打包在一起了，不需要单独的 tokenizer 文件就可以运行

**Comment by ljiuyuan1987** [comment]
> tokenizer 的 vocabulary 已经和模型打包在一起了，不需要单独的 tokenizer 文件就可以运行

谢谢
