### ISSUE TITLE
请问如何实现的量化？

### ISSUE THREAD

**Issue by lwo2002** [MegEngine/InferLLM#26]
请问chatglm6b是如何实现量化的？有量化代码吗？llamacpp可以做到吗？

**Comment by chenqy4933** [comment]
量化代码在：https://github.com/MegEngine/InferLLM/blob/main/application/chatglm/quantizer.cpp llama.cpp可以做到，但是需要你写一个 chatglm.cpp

**Comment by lwo2002** [comment]
> 量化代码在：https://github.com/MegEngine/InferLLM/blob/main/application/chatglm/quantizer.cpp llama.cpp可以做到，但是需要你写一个 chatglm.cpp

谢谢。
