### ISSUE TITLE
Compile error: void inferllm::BaiChuanGraph::constuct_llm()? marked ?override?, but does not override

### ISSUE THREAD

**Issue by cjia4** [MegEngine/InferLLM#43]
InferLLM$ cd build
abc:/media/disk0/chatbot/InferLLM/build$ cmake ..
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- current platform: x86_64
-- Configuring done
-- Generating done
-- Build files have been written to: /media/disk0/chatbot/InferLLM/build
abc:/media/disk0/chatbot/InferLLM/build$ make
[  2%] Building CXX object CMakeFiles/InferLLM.dir/src/core/device.cpp.o
[  4%] Building CXX object CMakeFiles/InferLLM.dir/src/core/graph.cpp.o
[  7%] Building CXX object CMakeFiles/InferLLM.dir/src/core/kvstotage.cpp.o
[  9%] Building CXX object CMakeFiles/InferLLM.dir/src/core/model.cpp.o
[ 11%] Building CXX object CMakeFiles/InferLLM.dir/src/core/model_imp.cpp.o
[ 14%] Building CXX object CMakeFiles/InferLLM.dir/src/core/op.cpp.o
[ 16%] Building CXX object CMakeFiles/InferLLM.dir/src/core/tensor.cpp.o
[ 19%] Building CXX object CMakeFiles/InferLLM.dir/src/core/thread_pool.cpp.o
[ 21%] Building CXX object CMakeFiles/InferLLM.dir/src/file.cpp.o
[ 23%] Building CXX object CMakeFiles/InferLLM.dir/src/graph/baichuan.cpp.o
In file included from /media/disk0/chatbot/InferLLM/src/graph/baichuan.cpp:1:
/media/disk0/chatbot/InferLLM/src/graph/baichuan.h:13:10: error: ?void inferllm::BaiChuanGraph::constuct_llm()? marked ?override?, but does not override
   13 |     void constuct_llm() override;
      |          ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/InferLLM.dir/build.make:202: CMakeFiles/InferLLM.dir/src/graph/baichuan.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/InferLLM.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

====git log

 git log
commit 11638dc8cfa7e5da53b9af2fb83aad062aea3dd6 (HEAD -> main, origin/main, origin/HEAD)
Merge: 2f68d78 846fa15
Author: Kewin <chenqiyou@megvii.com>
Date:   Tue Jun 27 10:42:36 2023 +0800

    Merge pull request #37 from IanVzs/main
    
    Fixed an undefined variable in a optimized_x86.h file

commit 2f68d788288577ee0c9b9c4ee18f943f6c5909d1
Merge: efc1c18 a39a512
Author: Kewin <chenqiyou@megvii.com>
Date:   Tue Jun 27 10:41:04 2023 +0800

    Merge pull request #39 from rejoicesyc/dev
    
    fix: fix typo

**Comment by cjia4** [comment]
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04.1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-aYxV0E/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-aYxV0E/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1)

**Comment by cjia4** [comment]
rg constuct_llm
src/graph/baichuan.h
13:    void constuct_llm() override;

src/graph/baichuan.cpp
58:    constuct_llm();
108:void BaiChuanGraph::constuct_llm(){

**Comment by cjia4** [comment]
源代码里面有拼写错误。最新代码里面的baichuan模型代码里面写的是constuct_llm 而不是 construct_llm   ， 少了一个r。
导致编译器报错

**Comment by chenqy4933** [comment]
应该是上午和入一个 PR 导致的
