### ISSUE TITLE
unsupported relocation 37 on musl libc

### ISSUE THREAD

**Issue by xhebox** [MegEngine/InferLLM#58]
It appeared after #46 . The compiler emit `REL_IRELTIV` symbols sometimes causing musl-libc failed to load the program.

The root cause seems that compiling optimized kernel and linking them seperately will introduce some strange changes. Here I mean linking these two together:

```
src/kern/naive.o
src/kern/optimized/xxx/kernel.o
```

I'll try to make them header-only somehow. And see if that works.

**Comment by chenqy4933** [comment]
👍

**Comment by xhebox** [comment]
Confirmed that it is an unrelated problem to inferllm itself. Though it is caused by the `avx/avx2` attribute dispatcher in #54.

**Comment by chenqy4933** [comment]
attribute dispatcher has many issues，sometime change with macro
