### ISSUE TITLE
ChatGLM2 效果异常

### ISSUE THREAD

**Issue by adf1178** [MegEngine/InferLLM#66]
我尝试下载了官方提供的 q4 模型，也尝试了自己对模型进行量化。但是加载后模型输出不正常
<img width="825" alt="image" src="https://github.com/MegEngine/InferLLM/assets/40065141/20be18ba-83ec-48d5-a16e-262f2e67de14">
<img width="850" alt="image" src="https://github.com/MegEngine/InferLLM/assets/40065141/2ec82956-182e-41bb-9823-1bcd0f3364c4">

**Comment by chenqy4933** [comment]
thanks, yes, there is bug, I fix in fd184735c95770ef5defeb1b94036f76cda118da
