### ISSUE TITLE
chatglm2 GPU版本的int4、int8量化模型预测结果异常

### ISSUE THREAD

**Issue by itfish1990** [MegEngine/InferLLM#67]
![image](https://github.com/MegEngine/InferLLM/assets/116904065/22ebdb67-3fb1-4cae-941d-bd49684b9502)

**Comment by chenqy4933** [comment]
![image](https://github.com/MegEngine/InferLLM/assets/18734791/74f64c60-30b5-46de-b602-2e8e9c2db5ac)

maybe there is a bug in an early commit， now it is ok in the main branch.
